/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.snake.view;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 *
 * @author Eduard
 */
public class BoardPanel extends javax.swing.JPanel implements ActionListener {

    public static final int PADDING_SMALL = 32;
    public static final int PADDING_LARGE = 45;
    
    private int boardWidth;
    private int boardHeight;
    private int cellSize;
    private Map<Color, List<Point>> cellColors =  new LinkedHashMap<>();
    
    /**
     * Creates new form BoardPanel
     */
    public BoardPanel() {
        initComponents();
        setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void setBoardWidth(int newWidth) {
        boardWidth = newWidth;
    }

    public void setBoardHeight(int newHeight) {
        boardHeight = newHeight;
    }
    
    public void setCellSize(int size) {
        cellSize = size;
    }

    public void setCellColors(Map<Color, List<Point>> cellColors) {
        this.cellColors = cellColors;
    }
    
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        draw(g);
    }
    
    public void draw(Graphics g) {
        
        // Obtener todos los elementos agrupados por color
        for (Color color : cellColors.keySet()) {
            g.setColor(color);
            List<Point> points = cellColors.get(color);
            for (Point point : points) {
                g.fillRect(point.x * cellSize, point.y * cellSize, cellSize, cellSize); 
            }
        }
        
        g.setColor(new Color(51,51,51));
        
        for (int i = 0; i <= boardWidth/cellSize; i++) {
            g.drawLine(i * cellSize, 0, i * cellSize, boardHeight);            
        }
        
        for (int i = 0; i <= boardHeight/cellSize; i++) {
            g.drawLine(0, i * cellSize, boardWidth, i * cellSize);
        }
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
