/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.snake.view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.border.BevelBorder;

/**
 *
 * @author Eduard
 */
public class ColorPanel extends javax.swing.JDialog {

    private Color selectedColor;
    private Color[] palette;
    private ActionListener colorChangedListener;
    
    /**
     * Creates new form ColorPanel
     */
    public ColorPanel(SnakeView gameView, Color[] palette, String title, ActionListener colorChangedListener) {
        super(gameView, title, true);
        
        this.palette = palette;
        this.colorChangedListener = colorChangedListener;
        
        initComponents();
        generatePalette();
        
        pack();
        setLocationRelativeTo(null);
        setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colorInnerPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        colorInnerPanel.setLayout(new java.awt.GridLayout(0, 3, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(colorInnerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(colorInnerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public Color getSelectedColor() {
        return selectedColor;
    }
    
    private void generatePalette() {
        
        for (Color color : palette) {
            JButton colorButton = new JButton();
            colorButton.setPreferredSize(new Dimension(50, 50));
            colorButton.setBackground(color);
            colorButton.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

            // Listener para cuando se selecciona un color
            colorButton.addActionListener(e -> {
                
                selectedColor = color;
                colorChangedListener.actionPerformed(e);
                
                this.dispose();
            });

            colorInnerPanel.add(colorButton);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel colorInnerPanel;
    // End of variables declaration//GEN-END:variables
}
