/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.snake.view;

import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Arrays;
import java.util.List;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author Eduard
 */
public class SettingsPanel extends javax.swing.JDialog {

    List<JComboBox<String>> comboBoxes;
    Random random = new Random();
    
    /**
     * Creates new form SettingsPanel
     */
    public SettingsPanel(MenuPanel menuPanel) {
        super(menuPanel, "Game Settings", true);
        initComponents();
        
        comboBoxes = Arrays.asList(boardCmb, speedCmb, foodCmb, effectCmb);
        
        pack();
        setLocationRelativeTo(null);
        setFocusable(true);
        setWindowClosingListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boardLabel = new javax.swing.JLabel();
        speedLabel = new javax.swing.JLabel();
        boardCmb = new javax.swing.JComboBox<>();
        foodLabel = new javax.swing.JLabel();
        speedCmb = new javax.swing.JComboBox<>();
        foodCmb = new javax.swing.JComboBox<>();
        effectLabel = new javax.swing.JLabel();
        effectCmb = new javax.swing.JComboBox<>();
        randomBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        playBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        boardLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        boardLabel.setText("Board");
        boardLabel.setPreferredSize(new java.awt.Dimension(60, 26));

        speedLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        speedLabel.setText("Speed");
        speedLabel.setPreferredSize(new java.awt.Dimension(60, 26));

        boardCmb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        foodLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        foodLabel.setText("Food");
        foodLabel.setPreferredSize(new java.awt.Dimension(60, 26));

        speedCmb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        speedCmb.setPreferredSize(new java.awt.Dimension(89, 26));

        foodCmb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        effectLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        effectLabel.setText("Effect");
        effectLabel.setPreferredSize(new java.awt.Dimension(60, 26));

        effectCmb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        effectCmb.setPreferredSize(new java.awt.Dimension(89, 26));

        randomBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        randomBtn.setText("Random");
        randomBtn.setPreferredSize(new java.awt.Dimension(100, 27));
        randomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomBtnActionPerformed(evt);
            }
        });

        resetBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        resetBtn.setText("Reset");
        resetBtn.setPreferredSize(new java.awt.Dimension(100, 27));
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        playBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        playBtn.setText("Play");
        playBtn.setPreferredSize(new java.awt.Dimension(100, 27));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(effectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(foodLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(speedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boardCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(speedCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(foodCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(effectCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(playBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(randomBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boardCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(speedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(speedCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(foodLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foodCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(effectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(effectCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(randomBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(playBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        for (JComboBox<String> comboBox : comboBoxes) {
            comboBox.setSelectedIndex(0);
        }
    }//GEN-LAST:event_resetBtnActionPerformed

    private void randomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomBtnActionPerformed
        
        for (JComboBox<String> comboBox : comboBoxes) {
            int itemCount = comboBox.getItemCount();
            if (itemCount > 0) {
                int randomIndex = random.nextInt(itemCount);
                comboBox.setSelectedIndex(randomIndex);
            }
        }
    }//GEN-LAST:event_randomBtnActionPerformed

    public void setPlaySettingsListener(ActionListener listener) {
        playBtn.addActionListener(listener);
    }
    
    public void setBoardCmbModel(String[] names, int selectedIndex) {
        boardCmb.setModel(new DefaultComboBoxModel<>(names));
        boardCmb.setSelectedIndex(selectedIndex);
    }
    
    public void setSpeedCmbModel(String[] names, int selectedIndex) {
        speedCmb.setModel(new DefaultComboBoxModel<>(names));
        speedCmb.setSelectedIndex(selectedIndex);
    }
    
    public void setFoodCmbModel(String[] names, int selectedIndex) {
        foodCmb.setModel(new DefaultComboBoxModel<>(names));
        foodCmb.setSelectedIndex(selectedIndex);
    }
    
    public void setEffectCmbModel(String[] names, int selectedIndex) {
        effectCmb.setModel(new DefaultComboBoxModel<>(names));
        effectCmb.setSelectedIndex(selectedIndex);
    }
    
    public int getBoardCmbSelectedIndex() {
        return boardCmb.getSelectedIndex();
    }
    
    public int getSpeedCmbSelectedIndex() {
        return speedCmb.getSelectedIndex();
    }
    
    public int getFoodCmbSelectedIndex() {
        return foodCmb.getSelectedIndex();
    }
    
    public int getEffectCmbSelectedIndex() {
        return effectCmb.getSelectedIndex();
    }
    
    public void setWindowClosingListener () {
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                playBtn.doClick();
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boardCmb;
    private javax.swing.JLabel boardLabel;
    private javax.swing.JComboBox<String> effectCmb;
    private javax.swing.JLabel effectLabel;
    private javax.swing.JComboBox<String> foodCmb;
    private javax.swing.JLabel foodLabel;
    private javax.swing.JButton playBtn;
    private javax.swing.JButton randomBtn;
    private javax.swing.JButton resetBtn;
    private javax.swing.JComboBox<String> speedCmb;
    private javax.swing.JLabel speedLabel;
    // End of variables declaration//GEN-END:variables
}
